name: Analyze
run-name: Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: jhae-de/jhae-de/.github/workflows/node-project-lint.yaml@main

  test:
    name: Test
    uses: jhae-de/jhae-de/.github/workflows/node-project-test.yaml@main
    with:
      test-script: 'test'
